GET http://localhost:3000/me/collection
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RuYW1lIjoiU2FyYWgiLCJsYXN0bmFtZSI6IkNyb2NoZSIsImVtYWlsIjoic2FyYWhAY3JvY2hlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJE0uYXZHOHlwWDVwMDV3a3dKU2ZBSE9IYklkV2NxTFFGL3Bib1hIOEZzZ2Fld1M4d2ZPN1BxIiwiYmlydGhkYXRlIjoiMTkwNS0wNS0wNFQyMzo1MDozOS4wMDBaIiwiZWNvY29pbnMiOjAsInNjb3JlIjowLCJyb2xlX2lkIjoyLCJpYXQiOjE2ODE1Nzg1NjksImV4cCI6MTY4MTU4MDM2OX0.XXd08GhvoZE5FQFvdwfjrjhNBCeT-yLCmRZBHYQ6j-s

###

GET http://localhost:3000/me/collection/card
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RuYW1lIjoiU2FyYWgiLCJsYXN0bmFtZSI6IkNyb2NoZSIsImVtYWlsIjoic2FyYWhAY3JvY2hlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJE0uYXZHOHlwWDVwMDV3a3dKU2ZBSE9IYklkV2NxTFFGL3Bib1hIOEZzZ2Fld1M4d2ZPN1BxIiwiYmlydGhkYXRlIjoiMTkwNS0wNS0wNFQyMzo1MDozOS4wMDBaIiwiZWNvY29pbnMiOjAsInNjb3JlIjowLCJyb2xlX2lkIjoyLCJpYXQiOjE2ODE1Nzg1NjksImV4cCI6MTY4MTU4MDM2OX0.XXd08GhvoZE5FQFvdwfjrjhNBCeT-yLCmRZBHYQ6j-s

###

POST http://localhost:3000/me/collection/card
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RuYW1lIjoiU2FyYWgiLCJsYXN0bmFtZSI6IkNyb2NoZSIsImVtYWlsIjoic2FyYWhAY3JvY2hlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJE0uYXZHOHlwWDVwMDV3a3dKU2ZBSE9IYklkV2NxTFFGL3Bib1hIOEZzZ2Fld1M4d2ZPN1BxIiwiYmlydGhkYXRlIjoiMTkwNS0wNS0wNFQyMzo1MDozOS4wMDBaIiwiZWNvY29pbnMiOjAsInNjb3JlIjowLCJyb2xlX2lkIjoyLCJpYXQiOjE2ODE1Nzg1NjksImV4cCI6MTY4MTU4MDM2OX0.XXd08GhvoZE5FQFvdwfjrjhNBCeT-yLCmRZBHYQ6j-s

{
    "card_id":11,
    "expiration_date":"01-01-2023"
}

###

PATCH http://localhost:3000/me/collection/card/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RuYW1lIjoiU2FyYWgiLCJsYXN0bmFtZSI6IkNyb2NoZSIsImVtYWlsIjoic2FyYWhAY3JvY2hlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJE0uYXZHOHlwWDVwMDV3a3dKU2ZBSE9IYklkV2NxTFFGL3Bib1hIOEZzZ2Fld1M4d2ZPN1BxIiwiYmlydGhkYXRlIjoiMTkwNS0wNS0wNFQyMzo1MDozOS4wMDBaIiwiZWNvY29pbnMiOjAsInNjb3JlIjowLCJyb2xlX2lkIjoyLCJpYXQiOjE2ODE1Nzg1NjksImV4cCI6MTY4MTU4MDM2OX0.XXd08GhvoZE5FQFvdwfjrjhNBCeT-yLCmRZBHYQ6j-s

###

DELETE http://localhost:3000/me/collection/card/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RuYW1lIjoiU2FyYWgiLCJsYXN0bmFtZSI6IkNyb2NoZSIsImVtYWlsIjoic2FyYWhAY3JvY2hlLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJE0uYXZHOHlwWDVwMDV3a3dKU2ZBSE9IYklkV2NxTFFGL3Bib1hIOEZzZ2Fld1M4d2ZPN1BxIiwiYmlydGhkYXRlIjoiMTkwNS0wNS0wNFQyMzo1MDozOS4wMDBaIiwiZWNvY29pbnMiOjAsInNjb3JlIjowLCJyb2xlX2lkIjoyLCJpYXQiOjE2ODE1Nzg1NjksImV4cCI6MTY4MTU4MDM2OX0.XXd08GhvoZE5FQFvdwfjrjhNBCeT-yLCmRZBHYQ6j-s

###

POST http://localhost:3000/sign-up
Content-Type: application/json

{
    "firstname": "Judas",
    "lastname": "Bricot",
    "email":"judas@bricot.com",
    "password":"Azerty123!",
    "confirmpassword": "Azerty123!",
    "birthdate": "05/05/190"
}

###

POST http://localhost:3000/sign-in
Content-Type: application/json

{
    "email":"sarah@croche.com",
    "password":"sarah"
}

###

POST http://localhost:3000/proposal
Content-Type: application/json

{
    "image":"image",
    "title":"test2",
    "description":"test",
    "environmental_rating":3,
    "economic_rating":3,
    "value": 50,
    "user_id":1
}