POST http://localhost:3000/sign-up
Content-Type: application/json

{
    "firstname": "Jean",
    "lastname": "Biance",
    "email":"jean.biance@gmail.com",
    "password":"Azerty123!",
    "confirmpassword": "Azerty123!",
    "birthdate": "05/05/1990"
}

###

POST http://localhost:3000/sign-in
Content-Type: application/json

{
    "email":"laura.teur@gmail.com",
    "password":"Azerty123!"
}

###

POST http://localhost:3000/sign-in
Content-Type: application/json

{
    "email":"jean.biance@gmail.com",
    "password":"Azerty1234!"
}

###

GET http://localhost:3000/me/collection
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RuYW1lIjoiTGF1cmEiLCJsYXN0bmFtZSI6IlRldXIiLCJlbWFpbCI6ImxhdXJhLnRldXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkR2lCN2pEdWg3SUdsUjNVaExwbXNKZVVGLjg0cnJVVjVwcVF0bWZkVHJ4SWlYRlZiSXdXSGkiLCJiaXJ0aGRhdGUiOiIxOTkwLTA1LTA0VDIyOjAwOjAwLjAwMFoiLCJlY29jb2lucyI6MCwic2NvcmUiOjAsInJvbGVfaWQiOjIsImNyZWF0ZWRfYXQiOiIyMDIzLTA0LTIwVDEyOjA5OjA2LjA4NloiLCJ1cGRhdGVkX2F0IjpudWxsLCJpYXQiOjE2ODIzMjIzODgsImV4cCI6MTY4MjMyNDE4OH0.yoI5RZmD6aK5I_7lloA2Es8Xv69qsT99Wa6rjvWrjvA

###s

GET http://localhost:3000/me/collection/card
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE

###

POST http://localhost:3000/me/collection/card
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RuYW1lIjoiTGF1cmEiLCJsYXN0bmFtZSI6IlRldXIiLCJlbWFpbCI6ImxhdXJhLnRldXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkR2lCN2pEdWg3SUdsUjNVaExwbXNKZVVGLjg0cnJVVjVwcVF0bWZkVHJ4SWlYRlZiSXdXSGkiLCJiaXJ0aGRhdGUiOiIxOTkwLTA1LTA0VDIyOjAwOjAwLjAwMFoiLCJlY29jb2lucyI6MCwic2NvcmUiOjAsInJvbGVfaWQiOjIsImNyZWF0ZWRfYXQiOiIyMDIzLTA0LTIwVDEyOjA5OjA2LjA4NloiLCJ1cGRhdGVkX2F0IjpudWxsLCJpYXQiOjE2ODIzMjIzODgsImV4cCI6MTY4MjMyNDE4OH0.yoI5RZmD6aK5I_7lloA2Es8Xv69qsT99Wa6rjvWrjvA

{
    "cardId":5,
    "expirationDate":"01-06-2023"
}

###

PATCH http://localhost:3000/me/collection/card/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RuYW1lIjoiTGF1cmEiLCJsYXN0bmFtZSI6IlRldXIiLCJlbWFpbCI6ImxhdXJhLnRldXJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkR2lCN2pEdWg3SUdsUjNVaExwbXNKZVVGLjg0cnJVVjVwcVF0bWZkVHJ4SWlYRlZiSXdXSGkiLCJiaXJ0aGRhdGUiOiIxOTkwLTA1LTA0VDIyOjAwOjAwLjAwMFoiLCJlY29jb2lucyI6MCwic2NvcmUiOjAsInJvbGVfaWQiOjIsImNyZWF0ZWRfYXQiOiIyMDIzLTA0LTIwVDEyOjA5OjA2LjA4NloiLCJ1cGRhdGVkX2F0IjpudWxsLCJpYXQiOjE2ODIzMjIzODgsImV4cCI6MTY4MjMyNDE4OH0.yoI5RZmD6aK5I_7lloA2Es8Xv69qsT99Wa6rjvWrjvA

###

DELETE http://localhost:3000/me/collection/card/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE

###

GET http://localhost:3000/proposal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE

###

POST http://localhost:3000/me/proposal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE

{
    "image": "data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII",
    "title":"titre8",
    "description":"description",
    "environmentalrating":3,
    "economicrating":3,
    "value": 50,
    "tags": []
}

###

PATCH http://localhost:3000/proposal/58
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE

###

GET http://localhost:3000/tag
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE

####

POST http://localhost:3000/tag
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE

{
    "name": "Truc",
    "color":"#123123"
}

####

PATCH http://localhost:3000/tag/20
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE

{
    "name": "Machin",
    "color":"#94a3b7"
}

####

DELETE http://localhost:3000/tag/20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE

####

GET http://localhost:3000/me/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlZSIsImVtYWlsIjoiamVhbi5iaWFuY2VAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkeHlNMVdKMzFEelFvcEkxN0RMTTBkdVpsTUFHdE90SmxCYy9IWU1IbnNsZk94SVQ3RndReE8iLCJiaXJ0aGRhdGUiOiIxOTkxLTA1LTA1VDIyOjAwOjAwLjAwMFoiLCJlY29jb2lucyI6MCwic2NvcmUiOjAsInJvbGVfaWQiOjEsImNyZWF0ZWRfYXQiOiIyMDIzLTA0LTIwVDEyOjA5OjA5LjkwOVoiLCJ1cGRhdGVkX2F0IjoiMjAyMy0wNC0yMVQxMzoyODowNC4wODlaIiwiaWF0IjoxNjgyMDg1NDY2LCJleHAiOjE2ODIwODcyNjZ9.CsQ4g8CZkgQNOoF_o5h4q67BMrN9Tu-9QorI2pJ0m3w

###

PATCH http://localhost:3000/me/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlZSIsImVtYWlsIjoiamVhbi5iaWFuY2VAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkeHlNMVdKMzFEelFvcEkxN0RMTTBkdVpsTUFHdE90SmxCYy9IWU1IbnNsZk94SVQ3RndReE8iLCJiaXJ0aGRhdGUiOiIxOTkxLTA1LTA1VDIyOjAwOjAwLjAwMFoiLCJlY29jb2lucyI6MCwic2NvcmUiOjAsInJvbGVfaWQiOjEsImNyZWF0ZWRfYXQiOiIyMDIzLTA0LTIwVDEyOjA5OjA5LjkwOVoiLCJ1cGRhdGVkX2F0IjoiMjAyMy0wNC0yMVQxMzoyODowNC4wODlaIiwiaWF0IjoxNjgyMDg1NDY2LCJleHAiOjE2ODIwODcyNjZ9.CsQ4g8CZkgQNOoF_o5h4q67BMrN9Tu-9QorI2pJ0m3w

{
    "firstname": "Jean",
    "lastname": "Biance",
    "email": "jean.biance@gmail.com",
    "password": "Azerty123!",
    "confirmpassword": "Azerty123!",
    "birthdate": "06/05/1991"
}

###

DELETE http://localhost:3000/me/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE

####

GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlZSIsImVtYWlsIjoiamVhbi5iaWFuY2VAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkeHlNMVdKMzFEelFvcEkxN0RMTTBkdVpsTUFHdE90SmxCYy9IWU1IbnNsZk94SVQ3RndReE8iLCJiaXJ0aGRhdGUiOiIxOTkxLTA1LTA1VDIyOjAwOjAwLjAwMFoiLCJlY29jb2lucyI6MCwic2NvcmUiOjAsInJvbGVfaWQiOjEsImNyZWF0ZWRfYXQiOiIyMDIzLTA0LTIwVDEyOjA5OjA5LjkwOVoiLCJ1cGRhdGVkX2F0IjoiMjAyMy0wNC0yMVQxMzoyODowNC4wODlaIiwiaWF0IjoxNjgyMDg1NDY2LCJleHAiOjE2ODIwODcyNjZ9.CsQ4g8CZkgQNOoF_o5h4q67BMrN9Tu-9QorI2pJ0m3w

###

PATCH http://localhost:3000/user/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlZSIsImVtYWlsIjoiamVhbi5iaWFuY2VAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkeHlNMVdKMzFEelFvcEkxN0RMTTBkdVpsTUFHdE90SmxCYy9IWU1IbnNsZk94SVQ3RndReE8iLCJiaXJ0aGRhdGUiOiIxOTkxLTA1LTA1VDIyOjAwOjAwLjAwMFoiLCJlY29jb2lucyI6MCwic2NvcmUiOjAsInJvbGVfaWQiOjEsImNyZWF0ZWRfYXQiOiIyMDIzLTA0LTIwVDEyOjA5OjA5LjkwOVoiLCJ1cGRhdGVkX2F0IjoiMjAyMy0wNC0yMVQxMzoyODowNC4wODlaIiwiaWF0IjoxNjgyMDg1NDY2LCJleHAiOjE2ODIwODcyNjZ9.CsQ4g8CZkgQNOoF_o5h4q67BMrN9Tu-9QorI2pJ0m3w

####

GET http://localhost:3000/me/card
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlZSIsImVtYWlsIjoiamVhbi5iaWFuY2VAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkeHlNMVdKMzFEelFvcEkxN0RMTTBkdVpsTUFHdE90SmxCYy9IWU1IbnNsZk94SVQ3RndReE8iLCJiaXJ0aGRhdGUiOiIxOTkxLTA1LTA1VDIyOjAwOjAwLjAwMFoiLCJlY29jb2lucyI6MCwic2NvcmUiOjAsInJvbGVfaWQiOjEsImNyZWF0ZWRfYXQiOiIyMDIzLTA0LTIwVDEyOjA5OjA5LjkwOVoiLCJ1cGRhdGVkX2F0IjoiMjAyMy0wNC0yMVQxMzoyODowNC4wODlaIiwiaWF0IjoxNjgyMDg1NDY2LCJleHAiOjE2ODIwODcyNjZ9.CsQ4g8CZkgQNOoF_o5h4q67BMrN9Tu-9QorI2pJ0m3w

###

GET http://localhost:3000/card
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE


####

PATCH http://localhost:3000/card/58
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE

{
    "title": "titre8",
    "description": "description2",
    "environmentalrating": 5,
    "economicrating": 3,
    "value": 55,
    "tags": [8]
}

# {
#     "image": "data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII",
#     "title": "titre8_mod",
#     "description": "description",
#     "environmentalrating": 3,
#     "economicrating": 3,
#     "value": 50,
#     "tags": [5,6]
# }

####

DELETE http://localhost:3000/card/53
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRuWGNUMUVuL2NWaWlaVWZaLjFpRUR1a0xHMDh4V1lOSnBwYjNSN0ZPRkhRQWpXc0RQTmJNYSIsImJpcnRoZGF0ZSI6IjE5OTAtMDUtMDRUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY4MjA4MzMzNSwiZXhwIjoxNjgyMDg1MTM1fQ.TSe0oM7SPh4tQhbz5TCiw_rR_M1GHejYN8yYezqxTuE
