@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiQmlhbmNlIiwiZW1haWwiOiJqZWFuLmJpYW5jZUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQwUmR5Y1lKbi42ZjFXUmhOaXhmQ0tleE00ZFNwclJPYjFFZTN1YXNYRnJZek5LUmkxV2RJVyIsImJpcnRoZGF0ZSI6IjE5OTEtMDUtMDVUMjI6MDA6MDAuMDAwWiIsImVjb2NvaW5zIjowLCJzY29yZSI6MCwicm9sZV9pZCI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMDQtMjBUMTI6MDk6MDkuOTA5WiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA0LTIxVDEzOjU4OjEyLjI4OVoiLCJpYXQiOjE2ODIzMzk2NzksImV4cCI6MTY4MjM0MTQ3OX0.Tv1ckKZhpe5jythhUPB6lbuB2soWsGmN3EvjKIk2S5w

###

POST http://localhost:3000/sign-up
Content-Type: application/json

{
    "firstname": "Jean",
    "lastname": "Biance",
    "email":"jean.biance@gmail.com",
    "password":"Azerty123!",
    "confirmpassword": "Azerty123!",
    "birthdate": "05/05/1990"
}

###

POST http://localhost:3000/sign-in
Content-Type: application/json

{
    "email":"laura.teur@gmail.com",
    "password":"Azerty123!"
}

###

POST http://localhost:3000/sign-in
Content-Type: application/json

{
    "email":"jean.biance@gmail.com",
    "password":"Azerty123!"
}

###

GET http://localhost:3000/me/collection
Authorization: {{token}}

###s

GET http://localhost:3000/me/collection/card
Authorization: {{token}}

###

POST http://localhost:3000/me/collection/card
Content-Type: application/json
Authorization: {{token}}

{
    "cardId":5,
    "expirationDate":"01-06-2023"
}

###

PATCH http://localhost:3000/me/collection/card/4
Authorization: {{token}}

###

DELETE http://localhost:3000/me/collection/card/5
Authorization: {{token}}

###

GET http://localhost:3000/proposal
Authorization: {{token}}

###

POST http://localhost:3000/me/proposal
Content-Type: application/json
Authorization: {{token}}

{
    "image": "data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII",
    "title":"titre8",
    "description":"description",
    "environmentalrating":3,
    "economicrating":3,
    "value": 50,
    "tags": []
}

###

PATCH http://localhost:3000/proposal/58
Authorization: {{token}}

###

GET http://localhost:3000/tag
Authorization: {{token}}

####

POST http://localhost:3000/tag
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Truc",
    "color":"#123123"
}

####

PATCH http://localhost:3000/tag/20
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Machin",
    "color":"#94a3b7"
}

####

DELETE http://localhost:3000/tag/20
Authorization: {{token}}

####

GET http://localhost:3000/me/user
Authorization: {{token}}

###

PATCH http://localhost:3000/me/user
Content-Type: application/json
Authorization: {{token}}

{
    "firstname": "Jean",
    "lastname": "Biance",
    "email": "jean.biance@gmail.com",
    "password": "Azerty123!",
    "confirmpassword": "Azerty123!",
    "birthdate": "06/05/1991"
}

###

DELETE http://localhost:3000/me/user
Authorization: {{token}}

####

GET http://localhost:3000/user
Authorization: {{token}}

###

PATCH http://localhost:3000/user/6
Authorization: {{token}}

####

GET http://localhost:3000/me/card
Authorization: {{token}}

###

GET http://localhost:3000/card
Authorization: Bearer {{token}}


####

PATCH http://localhost:3000/card/57
Content-Type: application/json
Authorization: {{token}}

{
    "title": "titre7",
    "description": "description2",
    "environmentalrating": 5,
    "economicrating": 3,
    "value": 55,
    "tags": [3,4,5,6]
}

# {
#     "image": "data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII",
#     "title": "titre8_mod",
#     "description": "description",
#     "environmentalrating": 3,
#     "economicrating": 3,
#     "value": 50,
#     "tags": [5,6]
# }

####

DELETE http://localhost:3000/card/53
Authorization: {{token}}
