# GET http://localhost:3000/collection/1

# POST http://localhost:3000/sign-up
# Content-Type: application/json

# {
#     "firstname": "Admin",
#     "lastname": "Admin",
#     "email":"admin@admin.com",
#     "password":"admin",
#     "confirmation": "admin",
#     "birthdate": "12/04/2023"
# }

# POST http://localhost:3000/sign-in
# Content-Type: application/json

# {
#     "email":"jean.bon@gmail.com",
#     "password":"jean",
#     "confirmation": "jean"
# }