GET http://localhost:3000/collection/1

###

PATCH http://localhost:3000/collection/1
Content-Type: application/json

{
    "state": true
}

###

POST http://localhost:3000/collection/1/create
Content-Type: application/json

{
    "image":"image",
    "title":"test",
    "description":"test",
    "environmental_rating":3,
    "economic_rating":3,
    "value": 50,
    "proposal":true,
    "user_id":1
}

###

GET http://localhost:3000/collection/1/add

###

POST http://localhost:3000/collection/1/add
Content-Type: application/json

{
    "user_id":1,
    "card_id":40,
    "expiration_date":"01-01-2024",
    "state":false
}